version: "3.8"

services:
  teams-bot:
    build: .
    ports:
      - "3978:3978"
    environment:
      # Bot Framework тохиргоо
      - BOT_ID=${BOT_ID}
      - BOT_PASSWORD=${BOT_PASSWORD}
      - BOT_TYPE=${BOT_TYPE}
      - BOT_TENANT_ID=${BOT_TENANT_ID}

      # OpenAI тохиргоо
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Python тохиргоо
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1

    volumes:
      # Development-д кодыг live reload хийхэд хэрэгтэй (production-д арилгах)
      - ./prompts:/app/prompts:ro

    restart: unless-stopped

    # Health check (FastAPI-ийн /health endpoint)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3978/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
